baseURL = 'https://g-ratie.github.io/hugo-profile/'
publishDir = "docs"
languageCode = 'ja-jp'
title = 'Profile'
theme = "PaperMod"
[params.profileMode]
enabled = true
title = "I'm Ratie "
subtitle = '作ったもの・やったこととか(準備中)'
imageUrl = 'https://github.com/g-ratie.png'
buttons = [
    { name = 'blog', url = '/blog' },
    { name = 'works', url = 'works' },
    # { name = 'about', url = '/about' }
]

[params]
socialIcons = [
    { name = 'twitter', url = 'https://twitter.com/ratie_iniad' },
    { name = 'github', url = 'https://github.com/g-Ratie'}
]
